### ISSUE TITLE
About fonts and color palette

### ISSUE THREAD

**Issue by markonikolas** [dceddia/css-layout-challenge#4]
Im having trouble identifying font for the logo, and the color palette doesent seem to match..
Could you please tell us what you used?

**Comment by dceddia** [comment]
Good question. My guess was Avenir Next, which is close but not exactly right. That's what I'm going with for now though. EDIT: To be clear, I didn't create this design, it's one I found on Dribbble [created by Imran](https://dribbble.com/shots/10747116-Cloud-Web-App).

Anyone else know what the font actually is? I tried screenshotting it and using some font-finding tools but they didn't turn up anything useful.

For colors, I dragged the image into Sketch and I've been using its color picker tool to figure out the color of elements. There are other ways though. On Mac there's the built-in [Digital Color Meter](https://www.howtogeek.com/228506/how-to-find-the-color-value-for-anything-on-your-mac%E2%80%99s-screen/), or you can drag the image into a browser and use the devtools color picker to figure out the colors. ([see here](https://superuser.com/questions/255647/how-to-pick-a-color-from-an-image))

**Comment by Perry-Hunchak** [comment]
Have you tried this?
https://www.myfonts.com/WhatTheFont/

**Comment by dceddia** [comment]
I tried a couple others but not that one! Just tried it with the text "Recently Used" and TT Commons Medium is a pretty close match. I'm not sure about that lowercase 't' but it's closer than Avenir at least.

**Comment by markonikolas** [comment]
After an hour long search, eventualy I went with **Lexend Deca**.
Font used for logo is not the same as that in the body of the page. For the body i think designer used **Raleway**

Fonts:
- https://fonts.google.com/specimen/Lexend+Deca
- https://fonts.google.com/specimen/Raleway


And for colors i used an extension for browser and i dont know is it me or colors are just a bit off..

Colors: 
- #343951
- #FFA000
- #F5F6FB

**Comment by dceddia** [comment]
Those are the same color values I got from sampling it in Sketch. They look about right to me though.

With a real-world design you'd hopefully be able to ask the designer 😄
