### ISSUE TITLE
[progress] Marko

### ISSUE THREAD

**Issue by markonikolas** [dceddia/css-layout-challenge#8]
Almost done, but i wont finish in time :slightly_frowning_face:  
![progress](https://user-images.githubusercontent.com/36996299/77561250-bce22400-6ebe-11ea-8337-c52acfd5e3cf.png)

**Comment by dceddia** [comment]
Looks great! Very close to done too. I didn't even have any of the arcs around the circle done in time. tbh this took me longer than I thought it would.
